project_name: kube-webhook-certgen

archives:
  - format: zip
    wrap_in_directory: "false"
    replacements:
      darwin: "macos"
      amd64: "x86_64"
    files:
      - none*

changelog:
  use: "github"

checksum:
  name_template: "checksums.txt"

dockers:
  -
    image_templates:
      - "dpejcev/kube-webhook-certgen:{{ .Major }}"
      - "dpejcev/kube-webhook-certgen:{{ .Major }}.{{ .Minor }}"
      - "dpejcev/kube-webhook-certgen:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "dpejcev/kube-webhook-certgen:latest"
    dockerfile: Dockerfile

dist: "build/dist"

release:
  draft: false
  header: |
    ## {{ .Version }} ({{ .Date }})
    See https://github.com/dejanzele/kube-webhook-certgen for download links and documentation
    ## Docker images
    - `docker pull dpejcev/kube-webhook-certgen:{{ .Major }}`
    - `docker pull dpejcev/kube-webhook-certgen:{{ .Major }}.{{ .Minor }}`
    - `docker pull dpejcev/kube-webhook-certgen:{{ .Major }}.{{ .Minor }}.{{ .Patch }}`
    - `docker pull dpejcev/kube-webhook-certgen:latest`

snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

builds:
  - id: "linux"
    goos:
      - "linux"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"
