name: release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  test:
    uses: "dejanzele/kube-webhook-certgen/.github/workflows/test.yaml@master"
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Golang"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"
      - name: "Login"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Cache"
        uses: "actions/cache@v3"
        with:
          path: "~/go/pkg/mod"
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          restore-keys: |
            ${{ runner.os }}-go-
      - name: "Modules"
        run: "go mod tidy"
      - name: "Release"
        uses: "goreleaser/goreleaser-action@v3"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "-f ./.goreleaser.yml release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
